### ISSUE TITLE
Great Work

### ISSUE THREAD

**Issue by devmondo** [holmstrom/Extinq#1]
hi, 
i really want to congratulate you on this small, but awesome librarary, i already started using it and it is so cool.

could i ask why you push towards IEnumerable instead ot ToList(), is it to make performance better ?

another thing, it would be great if you create a Tree Extension method so we can create tree like structure and add it to this lib

thanks in advanced. and good luck

**Comment by holmstrom** [comment]
I won't be implementing this as it is geared toward specific DB usage. This library is only aimed for Linq2Objects.
